# Monitoring and Observability for TradeWise AI
# ServiceMonitor for Prometheus
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tradewise-api-monitor
  namespace: tradewise-ai
  labels:
    app: tradewise-api
    monitoring: prometheus
spec:
  selector:
    matchLabels:
      app: tradewise-api
  endpoints:
  - port: http
    path: /api/performance/stats
    interval: 30s
    scrapeTimeout: 10s

---
# Prometheus Rules for Alerting
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: tradewise-alerts
  namespace: tradewise-ai
  labels:
    app: tradewise-ai
    monitoring: prometheus
spec:
  groups:
  - name: tradewise.performance
    rules:
    - alert: HighResponseTime
      expr: histogram_quantile(0.95, rate(flask_request_duration_seconds_bucket[5m])) > 0.5
      for: 5m
      labels:
        severity: warning
        service: tradewise-api
      annotations:
        summary: "High response time detected"
        description: "95th percentile response time is {{ $value }}s for 5 minutes"
    
    - alert: HighErrorRate
      expr: rate(flask_request_exceptions_total[5m]) / rate(flask_request_total[5m]) > 0.05
      for: 2m
      labels:
        severity: critical
        service: tradewise-api
      annotations:
        summary: "High error rate detected"
        description: "Error rate is {{ $value | humanizePercentage }} for 2 minutes"
    
    - alert: DatabaseConnectionFailed
      expr: increase(tradewise_db_connection_errors_total[5m]) > 0
      for: 1m
      labels:
        severity: critical
        service: tradewise-database
      annotations:
        summary: "Database connection errors"
        description: "Database connection errors detected"
    
    - alert: QueueBacklog
      expr: tradewise_task_queue_length > 50
      for: 5m
      labels:
        severity: warning
        service: tradewise-workers
      annotations:
        summary: "Task queue backlog"
        description: "Task queue has {{ $value }} pending tasks"
    
    - alert: LowCacheHitRate
      expr: tradewise_cache_hit_rate < 0.5
      for: 10m
      labels:
        severity: warning
        service: tradewise-cache
      annotations:
        summary: "Low cache hit rate"
        description: "Cache hit rate is {{ $value | humanizePercentage }}"

  - name: tradewise.infrastructure
    rules:
    - alert: PodCrashLooping
      expr: increase(kube_pod_container_status_restarts_total{namespace="tradewise-ai"}[15m]) > 0
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Pod is crash looping"
        description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is crash looping"
    
    - alert: PersistentVolumeUsageHigh
      expr: kubelet_volume_stats_used_bytes / kubelet_volume_stats_capacity_bytes > 0.85
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Persistent volume usage high"
        description: "PV {{ $labels.persistentvolumeclaim }} usage is {{ $value | humanizePercentage }}"

---
# Custom Metrics Exporter Service
apiVersion: v1
kind: Service
metadata:
  name: tradewise-metrics-service
  namespace: tradewise-ai
  labels:
    app: tradewise-api
    component: metrics
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: metrics
  selector:
    app: tradewise-api