# Kubernetes Secrets for TradeWise AI
# Note: In production, use external secret management (e.g., Vault, AWS Secrets Manager)
apiVersion: v1
kind: Secret
metadata:
  name: tradewise-secrets
  namespace: tradewise-ai
  labels:
    app: tradewise-ai
type: Opaque
stringData:
  # Application secrets (replace with actual values)
  SESSION_SECRET: "your-super-secure-session-secret-32-chars-plus"
  STRIPE_SECRET_KEY: "sk_live_your_stripe_live_secret_key_here"
  
  # Database secrets
  POSTGRES_PASSWORD: "your-secure-postgres-password"
  DATABASE_URL: "postgresql://tradewise_user:your-secure-postgres-password@postgres-service:5432/tradewise"
  
  # Redis secrets
  REDIS_PASSWORD: "your-secure-redis-password"
  REDIS_URL: "redis://:your-secure-redis-password@redis-service:6379/0"
  
  # Optional email configuration
  MAIL_USERNAME: "your-email@domain.com"
  MAIL_PASSWORD: "your-app-specific-password"

---
# Database secrets for PostgreSQL
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: tradewise-ai
  labels:
    app: postgres
type: Opaque
stringData:
  POSTGRES_PASSWORD: "your-secure-postgres-password"
  POSTGRES_USER: "tradewise_user"
  POSTGRES_DB: "tradewise"

---
# Redis secrets
apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
  namespace: tradewise-ai
  labels:
    app: redis
type: Opaque
stringData:
  REDIS_PASSWORD: "your-secure-redis-password"